# This file is required for the patch-validator to work and may contain advanced configuration options
# For more information, visit https://github.com/szapp/patch-validator/#configuration

prefix:
  - Patch_AE
ignore-declaration:
  - GIL_NONE
  - GIL_MIL
  - GIL_PAL
  - GIL_SLD
  - GIL_DJG
  - ITAR_MIL_M
  - Rtn_Start_44989
ignore-resource:
