# This file is required for the patch-validator to work and may contain advanced configuration options
# For more information, visit https://github.com/szapp/patch-validator/#configuration

prefix:
  - Patch_AE
ignore-declaration:
  # These symbols NEED to exist in the game
  - GIL_NONE
  - GIL_MIL
  - GIL_PAL
  - GIL_SLD
  - GIL_DJG
  - ITAR_MIL_M

  # This symbol has to be named that way (the routine of the NPC)
  - Rtn_Start_44989

  # The following symbols can cause problems. Ideally, they should be removed/replaced or checked dynamically.

  # DeadTreasureHunter.d
  - Npc_Default
  - GIL_BAU
  - NPCTYPE_AMBIENT
  - B_SetAttributesToChapter
  - FAI_HUMAN_STRONG
  - ITWR_BluePrint_StewarkArmor
  - ITMI_Gold
  - ITMI_Goldplate
  - ITMI_Silverring
  - ITMI_Silvercup
  - ITMI_SilverNecklace
  - ITMI_Goldcup
  - ITFO_Bacon
  - ITFO_Bread
  - ITFO_Cheese
  - ItPl_SwampHerb
  - ItMiSwordraw
  - ItMi_Zeitspalt_Addon
  - ItMi_Nugget
  - ItMw_Rubinklinge
  - B_SetNpcVisual
  - MALE
  - Face_N_OldBald_Jeremiah
  - BodyTex_N
  - ITAR_djg_crawler
  - B_GiveNpcTalents
  - B_SetFightSkills
  - TA_Stand_WP

  # Startup.d
  - B_KillNpc

  # DIA_ArmorExpansion.d
  - B_GiveInvItems
  - B_GivePlayerXP
  - B_LogEntry
  - B_LookAtNpc
  - B_TurnToNpc
  - DIA_Andre_LOBART_SUCCESS
  - DIA_Engor_Ruestung
  - DIA_Matteo_SellWhat
  - ItAr_MIL_L
  - ItAr_SLD_L
  - ItAt_Addon_KeilerFur
  - ItAt_wargfur
  - ItMi_Gold
  - ItMiSwordraw
  - Kapitel
  - Log_CreateTopic
  - LOG_NOTE
  - MIL_314_MORTIS
  - SLD_800_Lee
  - SLD_809_Bennet
  - SLD_811_Wolf
  - VLK_4108_Engor
  - VLK_416_Matteo
  - VLK_457_Brian
ignore-resource:
