//German Translation for version 1.2 done by iyumichan on Nexusmods.com, rest that was not finished was done by me with the help of machine translation

func void Patch_AE_LocalizeGerman() {
    // NPC
    Patch_AE_DeadTreasureHunter__name = "Toter Schatzjäger";

    // Blue print
    ItWr_BluePrint_StewarkArmor_ArmorExpansion__name = "Stewark Plattenrüstung-Schmiedeplan";
    Patch_AE_Use_Plan_StewarkArmor__line1 = "Stewark Plattenrüstung-Schmiedeplan";
    Patch_AE_Use_Plan_StewarkArmor__line2 = "Dies ist ein Schmiedeplan für alle begabten Schmiede aus Stewark. Hiermit sind sie verplichtet die Stadtwache mit neuen Rüstungen ausrüsten.";
    Patch_AE_Use_Plan_StewarkArmor__line3 = "Um eine Rüstung herzustellen brauchst du diese Materialien:";
    Patch_AE_Use_Plan_StewarkArmor__line4 = "-6 Rohstahl";
    Patch_AE_Use_Plan_StewarkArmor__line5 = "-3 Wargfelle";
    Patch_AE_Use_Plan_StewarkArmor__line6 = "Eine Anleitung zur Herstellung der Rüstung befindet sich auf der Rückseite.";
    Patch_AE_Use_Plan_StewarkArmor__line7 = "Das Verkaufen der Materialien oder des Schmiedeplans ist eine strafbare Handlung.";
    Patch_AE_Use_Plan_StewarkArmor__line8 = "Dies ist ein Befehl des Commandanten Cenrin der Stadtwache.";

    // Armor names
    ITAR_DJG_CrawlerP_ArmorExpansion__name = "Crawler Platte Jagd Rüstung";
    ITAR_PAL_H_ArmorExpansion__name = "Paladinrüstung";
    ITAR_MIL_H_ArmorExpansion__name = "Schwere Milizrüstung";
    ITAR_MILP_H_ArmorExpansion__name = "Schwere Armbrustschützen Milizrüstung";
    ITAR_GAMBESON_ArmorExpansion__name = "Jäger Stoffrüstung";
    ITAR_PAL_A_ArmorExpansion__name = "Angereicherte Paladinrüstung";
    ITAR_PAL_R_ArmorExpansion__name = "Rostige Paladinrüstung";
    ITAR_PAL_F_ArmorExpansion__name = "Reparierte Paladinrüstung";
    ITAR_PAL_C_ArmorExpansion__name = "Armbrustschützen Ritterrüstung";
    ITAR_PAL_CM_ArmorExpansion__name = "Schwere Armbrustschützen Ritterrüstung";
    ITAR_MIL_Med2_ArmorExpansion__name = "Verbesserte Mittlere Milizrüstung";
    ITAR_MIL_P_ArmorExpansion__name = "Armbrustschützen Milizrüstung";
    ITAR_MIL_M__name = "Mittlere Milizrüstung";
    ITAR_DJG_CL_ArmorExpansion__name = "Leichte DrachenverfolgerRüstung";
    ITAR_SLD_BOW_ArmorExpansion__name = "Schwere Söldner-Jagdrüstung";
    ITAR_MIL_R_ArmorExpansion__name = "Verbesserte Leichte Milizrüstung";
    ITAR_CRUSADER_ArmorExpansion__name = "Kreuzritterrüstung";
    ITAR_SLD_SCOUT_ArmorExpansion__name = "Leichte Söldner-Jagdrüstung";
    ITAR_SLD_MP_ArmorExpansion__name = "Mittlere Söldner-Jagdrüstung";
    ITAR_MIL_SCOUT_ArmorExpansion__name = "Rüstung eines Armbrustschützen-Rekruten der Miliz";
    ITAR_SLD_R_ArmorExpansion__name = "Verbesserte Mittlere Söldnerrüstung";
    ITAR_SLD_LR_ArmorExpansion__name = "Verbesserte Leichte Söldnerrüstung";
    ITAR_PAL_CH_ArmorExpansion__name = "Armbrustschützen Paladinrüstung";
    ITAR_DJG_CH_ArmorExpansion__name = "Schwere DrachenverfolgerRüstung";
    ITAR_DJG_CM_ArmorExpansion__name = "Mittlere DrachenverfolgerRüstung";
    ITAR_PAL_ST_ArmorExpansion__name = "Stewark Plattenrüstung";
    ITAR_PAL_MH_ArmorExpansion__name = "Schwere Ritterrüstung";
    ITAR_PIR_H_ArmorExpansion__name = "Kapitäns Mantel";
    ITAR_PAL_ANH_ArmorExpansion__name = "Angereicherte Paladinrüstung";
    ITAR_PAL_RNH_ArmorExpansion__name = "Rostige Paladinrüstung";
    ITAR_PAL_FNH_ArmorExpansion__name = "Reparierte Paladinrüstung";
    ITAR_PAL_AFH_ArmorExpansion__name = "Angereicherte Paladinrüstung";
    ITAR_PAL_RFH_ArmorExpansion__name = "Rostige Paladinrüstung";
    ITAR_PAL_FFH_ArmorExpansion__name = "Reparierte Paladinrüstung";
    ITAR_NH_CRUSADER_ArmorExpansion_name = "Kreuzritterrüstung";
    ITAR_ARX_HUNTERM_ArmorExpansion__name = "Jagdjacke";
    ITAR_ARX_HUNTERH_ArmorExpansion__name = "Verstärkte Jagdjacke";
    ITAR_KDF_M_ArmorExpansion__name = "Mittlere Feuerrobe";
    ITAR_DJG_H_ArmorExpansion__name = "Schwere Drachenjägerrüstung";
    ITAR_DJG_M_ArmorExpansion__name = "Mittlere Drachenjägerrüstung";

    // Armor bonus
    Patch_AE_TEXT_MaxManaBonus20 = "+20 Maximaler Mana Bonus";
    Patch_AE_TEXT_MaxManaBonus40 = "+40 Maximaler Mana Bonus";
    Patch_AE_TEXT_OldArmor = "Diese Rüstung hat seine besten Tage schon hinter sich.";
    Patch_AE_TEXT_ArcheryBonus3 = "+3% Bogen Bonus";
    Patch_AE_TEXT_ArcheryBonus5 = "+5% Bogen Bonus";
    Patch_AE_TEXT_ArcheryBonus6 = "+6% Bogen Bonus";
    Patch_AE_TEXT_TwoHandedBonus5 = "+5% Zweihand Bonus";
    Patch_AE_TEXT_DexBonus10_OneHandedBonus10 = "+10 Geschicklichkeit Bonus, +10% Einhand Bonus";

    // Alerts: The constants used to create an alert (print on a screen) about missing ingredient(s) or an forged armor.
    Patch_AE_PRINT_ProdItemsMissing__SUBSTR_1 = "Fehlende Materialen: ";
    Patch_AE_PRINT_ProdItemsMissing__SUBSTR_2 = " x";
    Patch_AE_PRINT_ForgeSuccess = " geschmiedet!";

    // ==============
    //    DIALOGS
    // ==============

    // ------
    // Andre
    // ------

    Patch_AE_DIA_ANDRE_MILITIA_ARMORREWARD_MELEE = "(Wählen Sie Mittlere Milizrüstung)";
    Patch_AE_DIA_ANDRE_MILITIA_ARMORREWARD_RANGED = "(Wählen Sie eine mittlere Miliz-Armbrustschützenrüstung)";
    Patch_AE_DIA_ANDRE_MIL_SCOUTArmor_desc = "Hast du keine leichtere Rüstung für mich? (Leichte Milizrüstung ersetzen)";
    // AI_Output(other, self, "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_01_DE"); //Hast du keine leichtere Rüstung für mich?
    // AI_Output(other, self, "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_02_DE"); //Ich halte lieber Abstand.
    // AI_Output(self, other, "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_13_03_DE"); //Ich kann deine Rüstung gegen die Rüstung eines Armbrustschützen tauschen. Sie ist leichter als die Standardausrüstung, sodass du beweglicher, aber auch verwundbarer bist.
    // AI_Output(other, self, "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_04_DE"); //Ich nehme es.
    // AI_Output(other, self, "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_9_DE"); //Hier, lass es dir gut dienen.

    // AI_Output(self, other, "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_03_DE"); //Sie haben alle meine Aufgaben erledigt.
    // AI_Output(self, other, "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_04_DE"); //Sie haben mir bewiesen, dass Sie eine Beförderung verdienen.
    // AI_Output(self, other, "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_05_DE"); //Bitte sehr, mittlere Milizrüstung.
    // AI_Output(self, other, "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_06_DE"); //Ich hoffe, es wird Ihnen gute Dienste leisten, Soldat.
    // AI_Output(other, self, "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_15_01_DE"); //Danke.

    // Localized OU (do not change)
    PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_01 = "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_01_DE";
    PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_02 = "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_02_DE";
    PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_13_03 = "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_13_03_DE";
    PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_04 = "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_04_DE";
    PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_9 = "PATCH_AE_DIA_ANDRE_MIL_SCOUTARMOR_15_9_DE";
    PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_03 = "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_03_DE";
    PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_04 = "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_04_DE";
    PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_05 = "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_05_DE";
    PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_06 = "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_01_06_DE";
    PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_15_01 = "PATCH_AE_DIA_ANDRE_MILITIA_ARMORREWARD_15_01_DE";

    // ------
    // Bennet
    // ------

    Patch_AE_TOPIC_BENNET_ARMOR = "Söldnerrüstung-Verbesserungen.";

    Patch_AE_DIA_BENNET_SLDARMORASK_desc = "Hast du keine bessere Rüstung für mich?";
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_SLDARMORASK_15_01_DE"); //Hast du keine bessere Rüstung für mich?
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLDARMORASK_13_02_DE"); //Nein, nur Lee kann Rüstungen ausgeben.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLDARMORASK_13_03_DE"); //Aber ich kann das, was Sie bereits haben, verbessern. Das wird Sie allerdings etwas kosten.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_SLDARMORASK_15_04_DE"); //Was brauchst du dafür?
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLDARMORASK_13_05_DE"); //Die Materialien zur Herstellung bringst Du selbst mit, ich fertige es nicht aus eigenen Vorräten.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLDARMORASK_13_07_DE"); //Und ich arbeite nicht umsonst, also legen Sie auch etwas Gold bereit.
    Patch_AE_DIA_BENNET_SLDARMORASK_entry = "Bennet kann meine Söldnerrüstungen verbesseren, wenn ich ihm Gold und Materialien bringe.";

    Patch_AE_DIA_BENNET_SLD_LReforgedHUH_desc = "Ich will meine leichte Rüstung verbessern.";
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_15_01_DE"); //Ich will meine leichte Rüstung verbessern.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_15_04_DE"); //Was brauchen Sie dafür?
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_13_06_DE"); //Für eine leichte Rüstung genügen zwei Stahlstangen und zwei Wolfsfelle.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_13_07_DE"); //Ich verlange dafür 200 Goldstücke von Ihnen.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_15_09_DE"); //Ok.
    Patch_AE_DIA_BENNET_SLD_LReforgedHUH_entry = "Um meine leichte Rüstung zu verbessern braucht Bennet zwei Stück Rohstahl, zwei Wolfsfelle und 200 Gold.";

    Patch_AE_DIA_BENNET_SLD_LReforgedArmor_desc = "Ich habe alle Materialien um meine leichte Rüstung zu verbessern.";
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_15_01_DE"); //Ich habe alle Materialien um meine leichte Rüstung zu verbessern.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_15_11_DE"); //Bitte schön.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_12_DE"); //Okay, dann schauen wir es uns mal an.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_13_DE"); //Erledigt.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_14_DE"); //Hier ist es, ich denke, ich habe gute Arbeit geleistet.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_15_15_DE"); //Danke schön.
    Patch_AE_DIA_BENNET_SLD_LReforgedArmor_entry = "Bennet hat meine leichte Rüstung verbessert.";
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_16_DE"); //Komm wieder, wenn du alles dabei hast.

    Patch_AE_DIA_BENNET_MERC_MReforgedHUH_desc = "Ich will meine mittlere Rüstung verbessern.";
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_15_01_DE"); //Ich will meine mittlere Rüstung verbessern.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_15_03_DE"); //Was brauchen Sie dafür?
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_13_04_DE"); //Für die mittlere Rüstung benötigen Sie mehr als beim letzten Mal.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_13_05_DE"); //Drei Rohstahlbarren und eine Warg-Haut.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_13_06_DE"); //Ich brauche, sagen wir, 650 Gold, um es zu schaffen.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_15_08_DE"); //Ok.
    Patch_AE_DIA_BENNET_MERC_MReforgedHUH_entry = "Um meine mittlere Rüstung zu verbessern braucht Bennet drei Stück Rohstahl, ein Wargfell und 650 Gold.";

    Patch_AE_DIA_BENNET_MERC_MReforgedArmor_desc = "Ich habe alle Materialien um meine mittlere Rüstung zu verbessern.";
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_15_01_DE"); //Ich habe alle Materialien um meine mittlere Rüstung zu verbessern.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_15_10_DE"); //Bitte schön.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_11_DE"); //Okay, dann schauen wir es uns mal an.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_12_DE"); //Erledigt.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_13_DE"); //Hier ist es, ich denke, ich habe gute Arbeit geleistet.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_15_14_DE"); //Danke schön.
    Patch_AE_DIA_BENNET_MERC_MReforgedArmor_entry = "Bennet hat meine mittlere Rüstung verbessert.";
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_16_DE"); //Komm wieder, wenn du alles dabei hast.

    Patch_AE_DIA_BENNET_PAL_REFORGE_desc = "Kannst du diese rostige Paladinrüstung für mich reparieren?";
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_PAL_REFORGE_4_1_DE"); //Kannst du diese rostige Paladinrüstung für mich reparieren?
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_PAL_REFORGE_3_01_DE"); //Es tut mir leid, aber das kann ich nicht.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_PAL_REFORGE_3_03_DE"); //Ich habe nichts gegen Sie, schließlich haben Sie mich aus dem Gefängnis geholt.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_PAL_REFORGE_3_04_DE"); //Aber was würden die anderen auf dem Hof denken, wenn ich hier anfangen würde, Paladin-Rüstungen zu reparieren?
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_PAL_REFORGE_3_05_DE"); //Ihr müsst einen anderen Schmied finden.
    Patch_AE_DIA_BENNET_PAL_REFORGE_entry = "Bennet wird meine Rüstung nicht reparieren.";

    Patch_AE_DIA_Bennet_CROSSBOW_desc = "Hast du keine leichtere Rüstung für mich? (Leichte Drachenjägerrüstung ersetzen)";
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_CROSSBOW_15_01_DE"); //Hast du keine leichtere Rüstung für mich?
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_CROSSBOW_15_02_DE"); //Verstehen Sie mich nicht falsch, ich bin dankbar dafür, aber ich würde etwas weniger Schweres vorziehen.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_CROSSBOW_13_03_DE"); //Ja, ich habe auch so eine gemacht, wenn Sie wollen, kann ich sie für Sie austauschen.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_CROSSBOW_15_04_DE"); //Danke, ich nehme es.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_CROSSBOW_15_9_DE"); //Hier ist sie, möge sie Ihnen gute Dienste leisten.

    Patch_AE_DIA_Bennet_PATCH_DJG_ARMOR_CM_desc = "Mittlere DrachenverfolgerRüstung (12000 Gold)";
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_15_00_DE"); //Ich werde die Rüstung kaufen.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_06_01_DE"); //Oh, großartig. Es wird dir gefallen.
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_15_02_DE"); //Bei diesem Preis hoffe ich das.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_06_03_DE"); //Sie werden sehen, es war den Preis wert.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_06_04_DE"); //Sie haben nicht genug Gold bei sich.

    Patch_AE_DIA_Bennet_PATCH_DJG_ARMOR_CH_desc = "Schwere DrachenverfolgerRüstung (20000 Gold)";
    // AI_Output(other, self, "PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_15_00_DE"); //Gib mir die Rüstung.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_06_01_DE"); //Das ist die beste Rüstung, die ich je gemacht habe.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_06_02_DE"); //Es ist ein wahres Meisterwerk.
    // AI_Output(self, other, "PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_06_03_DE"); //Sie haben nicht genug Gold bei sich.

    // Localized OU (do not change)
    PATCH_AE_DIA_BENNET_SLDARMORASK_15_01 = "PATCH_AE_DIA_BENNET_SLDARMORASK_15_01_DE";
    PATCH_AE_DIA_BENNET_SLDARMORASK_13_02 = "PATCH_AE_DIA_BENNET_SLDARMORASK_13_02_DE";
    PATCH_AE_DIA_BENNET_SLDARMORASK_13_03 = "PATCH_AE_DIA_BENNET_SLDARMORASK_13_03_DE";
    PATCH_AE_DIA_BENNET_SLDARMORASK_15_04 = "PATCH_AE_DIA_BENNET_SLDARMORASK_15_04_DE";
    PATCH_AE_DIA_BENNET_SLDARMORASK_13_05 = "PATCH_AE_DIA_BENNET_SLDARMORASK_13_05_DE";
    PATCH_AE_DIA_BENNET_SLDARMORASK_13_07 = "PATCH_AE_DIA_BENNET_SLDARMORASK_13_07_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_15_01 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_15_01_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_15_04 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_15_04_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_13_06 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_13_06_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_13_07 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_13_07_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_15_09 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDHUH_15_09_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_15_01 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_15_01_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_15_11 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_15_11_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_12 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_12_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_13 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_13_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_14 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_14_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_15_15 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_15_15_DE";
    PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_16 = "PATCH_AE_DIA_BENNET_SLD_LREFORGEDARMOR_13_16_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_15_01 ="PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_15_01_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_15_03 ="PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_15_03_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_13_04 ="PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_13_04_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_13_05 ="PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_13_05_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_13_06 ="PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_13_06_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_15_08 ="PATCH_AE_DIA_BENNET_MERC_MREFORGEDHUH_15_08_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_15_01 = "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_15_01_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_15_10 = "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_15_10_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_11 = "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_11_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_12 = "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_12_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_13 = "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_13_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_15_14 = "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_15_14_DE";
    PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_16 = "PATCH_AE_DIA_BENNET_MERC_MREFORGEDARMOR_13_16_DE";
    PATCH_AE_DIA_BENNET_PAL_REFORGE_4_1 = "PATCH_AE_DIA_BENNET_PAL_REFORGE_4_1_DE";
    PATCH_AE_DIA_BENNET_PAL_REFORGE_3_01 = "PATCH_AE_DIA_BENNET_PAL_REFORGE_3_01_DE";
    PATCH_AE_DIA_BENNET_PAL_REFORGE_3_03 = "PATCH_AE_DIA_BENNET_PAL_REFORGE_3_03_DE";
    PATCH_AE_DIA_BENNET_PAL_REFORGE_3_04 = "PATCH_AE_DIA_BENNET_PAL_REFORGE_3_04_DE";
    PATCH_AE_DIA_BENNET_PAL_REFORGE_3_05 = "PATCH_AE_DIA_BENNET_PAL_REFORGE_3_05_DE";
    PATCH_AE_DIA_BENNET_CROSSBOW_15_01 = "PATCH_AE_DIA_BENNET_CROSSBOW_15_01_DE";
    PATCH_AE_DIA_BENNET_CROSSBOW_15_02 = "PATCH_AE_DIA_BENNET_CROSSBOW_15_02_DE";
    PATCH_AE_DIA_BENNET_CROSSBOW_13_03 = "PATCH_AE_DIA_BENNET_CROSSBOW_13_03_DE";
    PATCH_AE_DIA_BENNET_CROSSBOW_15_04 = "PATCH_AE_DIA_BENNET_CROSSBOW_15_04_DE";
    PATCH_AE_DIA_BENNET_CROSSBOW_15_9 = "PATCH_AE_DIA_BENNET_CROSSBOW_15_9_DE";
    PATCH_AE_DIA_BENNET_DJG_ARMOR_M_15_00 = "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_15_00_DE";
    PATCH_AE_DIA_BENNET_DJG_ARMOR_M_06_01 = "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_06_01_DE";
    PATCH_AE_DIA_BENNET_DJG_ARMOR_M_15_02 = "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_15_02_DE";
    PATCH_AE_DIA_BENNET_DJG_ARMOR_M_06_03 = "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_06_03_DE";
    PATCH_AE_DIA_BENNET_DJG_ARMOR_M_06_04 = "PATCH_AE_DIA_BENNET_DJG_ARMOR_M_06_04_DE";
    PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_15_00 = "PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_15_00_DE";
    PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_06_01 = "PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_06_01_DE";
    PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_06_02 = "PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_06_02_DE";
    PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_06_03 = "PATCH_AE_DIA_BENNET_PATCH_DJG_ARMOR_CH_06_03_DE";

    // ------
    // Brian
    // ------

    Patch_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_desc = "Ich brauche mehr Rohstahl.";
    // AI_Output(other, self, "PATCH_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_15_01_DE"); //Ich brauche mehr Rohstahl.
    // AI_Output(self, other, "PATCH_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_13_02_DE"); //Ich kann Ihnen einige meiner eigenen Vorräte verkaufen, aber das wird Sie viel kosten.
    // AI_Output(self, other, "PATCH_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_13_03_DE"); //200 pro Stück.

    Patch_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_desc = "Verkauf mir ein Stück Rohstahl. (200 Gold).";
    // AI_Output(other, self, "PATCH_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_4_1_DE"); //Verkaufen Sie mir ein Stück Rohstahl.
    // AI_Output(self, other, "PATCH_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_4_2_DE"); //Hier ist sie.
    // AI_Output(self, other, "PATCH_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_4_3_DE"); //Kommen Sie wieder, wenn Sie genug Gold bei sich haben.

    // Localized OU (do not change)
    PATCH_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_15_01 = "PATCH_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_15_01_DE";
    PATCH_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_13_02 = "PATCH_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_13_02_DE";
    PATCH_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_13_03 = "PATCH_AE_DIA_BRIAN_BUYRAWSTEEL_PATCHOC_13_03_DE";
    PATCH_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_4_1 = "PATCH_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_4_1_DE";
    PATCH_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_4_2 = "PATCH_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_4_2_DE";
    PATCH_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_4_3 = "PATCH_AE_DIA_PATCHOC_BRIAN_IWANNABUYSOMESTEEL_4_3_DE";

    // ------
    // Carl
    // ------

    Patch_AE_DIA_CARL_PAL_REFORGE_desc = "Kannst du diese rostige Paladinrüstung für mich reparieren?";
    // AI_Output(other, self, "PATCH_AE_DIA_CARL_PAL_REFORGE_4_1_DE"); //Kannst du diese rostige Paladinrüstung für mich reparieren?
    // AI_Output(self, other, "PATCH_AE_DIA_CARL_PAL_REFORGE_3_01_DE"); //Paladin-Rüstung?
    // AI_Output(self, other, "PATCH_AE_DIA_CARL_PAL_REFORGE_3_02_DE"); //Tut mir leid, Junge, aber das ist zu kompliziert für mich.
    // AI_Output(self, other, "PATCH_AE_DIA_CARL_PAL_REFORGE_3_03_DE"); //Ihr müsst einen anderen Schmied finden.
    Patch_AE_DIA_CARL_PAL_REFORGE_entry = "Carl wird meine Rüstung nicht reparieren.";

    // Localized OU (do not change)
    PATCH_AE_DIA_CARL_PAL_REFORGE_4_1 = "PATCH_AE_DIA_CARL_PAL_REFORGE_4_1_DE";
    PATCH_AE_DIA_CARL_PAL_REFORGE_3_01 = "PATCH_AE_DIA_CARL_PAL_REFORGE_3_01_DE";
    PATCH_AE_DIA_CARL_PAL_REFORGE_3_02 = "PATCH_AE_DIA_CARL_PAL_REFORGE_3_02_DE";
    PATCH_AE_DIA_CARL_PAL_REFORGE_3_03 = "PATCH_AE_DIA_CARL_PAL_REFORGE_3_03_DE";

    // ------
    // Engor
    // ------

    Patch_AE_DIA_engor_ARCHER_KAUFEN_desc = "Armbrustschützen-Milizrüstung kaufen (2300 Gold)";
    // AI_Output(other, self, "PATCH_AE_DIA_engor_ARCHER_KAUFEN_15_00_DE"); //Gib mir die Rüstung.
    // AI_Output(self, other, "PATCH_AE_DIA_engor_ARCHER_KAUFEN_13_01_DE"); //Hier ist es, es wird dich gut schützen, es ist ein verdammt gutes Stück.
    // AI_Output(self, other, "PATCH_AE_DIA_engor_ARCHER_KAUFEN_13_02_DE"); //Bringt mir zuerst das Gold.

    // Localized OU (do not change)
    PATCH_AE_DIA_engor_ARCHER_KAUFEN_15_00 = "PATCH_AE_DIA_engor_ARCHER_KAUFEN_15_00_DE";
    PATCH_AE_DIA_engor_ARCHER_KAUFEN_13_01 = "PATCH_AE_DIA_engor_ARCHER_KAUFEN_13_01_DE";
    PATCH_AE_DIA_engor_ARCHER_KAUFEN_13_02 = "PATCH_AE_DIA_engor_ARCHER_KAUFEN_13_02_DE";

    // ------
    // Garond
    // ------

    Patch_AE_DIA_GAROND_KNIGHT_ARMORREWARD_MELEE = "(Wählen Sie eine schwere Ritterrüstung)";
    Patch_AE_DIA_GAROND_KNIGHT_ARMORREWARD_RANGED = "(Wählen Sie eine schwere Ritter-Armbrustschützenrüstung)";
    // AI_Output(self, other, "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_03_DE"); //Warte!
    // AI_Output(self, other, "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_04_DE"); //You are the only one of us who has managed to kill a dragon so far.
    // AI_Output(self, other, "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_05_DE"); //Ich hoffe, dass Sie sie alle bekommen können.
    // AI_Output(self, other, "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_06_DE"); //Hier, das sollte euch bei eurer Mission helfen. Jetzt geh, wir haben keine Zeit zu verlieren.
    // AI_Output(other, self, "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_15_01_DE"); //Danke.

    // Localized OU (do not change)
    PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_03 = "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_03_DE";
    PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_04 = "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_04_DE";
    PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_05 = "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_05_DE";
    PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_06 = "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_01_06_DE";
    PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_15_01 = "PATCH_AE_DIA_GAROND_KNIGHT_ARMORREWARD_15_01_DE";

    // ------
    // Gorax
    // ------

    Patch_AE_DIA_Gorax_KDFM_ASK_desc = "Kann ich eine bessere Robe des Feuers bekommen?";
    // AI_Output(other, self, "PATCH_AE_DIA_Gorax_KDFM_ASK_3_03_DE"); //Kann ich eine bessere Robe des Feuers bekommen?
    // AI_Output(self, other, "PATCH_AE_DIA_Gorax_KDFM_ASK_3_04_DE"); //Ja, für eine kleine Spende an das Kloster werde ich dich mit einer besseren Robe des Feuers belohnen.
    // AI_Output(other, self, "PATCH_AE_DIA_Gorax_KDFM_ASK_3_05_DE"); //Wie hoch ist die Spende?
    // AI_Output(self, other, "PATCH_AE_DIA_Gorax_KDFM_ASK_3_06_DE"); //1500 Gold sollten genug sein.

    Patch_AE_DIA_Gorax_KDFM_BUY_desc = "Mittlere Feuerrobe kaufen (Schutz: 55/55/30/30, Preis: 1500 Gold)";
    // AI_Output(other, self, "PATCH_AE_DIA_Gorax_KDFM_BUY_4_1_DE"); //Ich bringe eine Spende für das Kloster.
    // AI_Output(self, other, "PATCH_AE_DIA_Gorax_KDFM_BUY_4_2_DE"); //Großartig, hier ist dein Feuergewand.

    // Localized OU (do not change)
    PATCH_AE_DIA_Gorax_KDFM_ASK_3_03 = "PATCH_AE_DIA_Gorax_KDFM_ASK_3_03_DE";
    PATCH_AE_DIA_Gorax_KDFM_ASK_3_04 = "PATCH_AE_DIA_Gorax_KDFM_ASK_3_04_DE";
    PATCH_AE_DIA_Gorax_KDFM_ASK_3_05 = "PATCH_AE_DIA_Gorax_KDFM_ASK_3_05_DE";
    PATCH_AE_DIA_Gorax_KDFM_ASK_3_06 = "PATCH_AE_DIA_Gorax_KDFM_ASK_3_06_DE";
    PATCH_AE_DIA_Gorax_KDFM_BUY_4_1 = "PATCH_AE_DIA_Gorax_KDFM_BUY_4_1_DE";
    PATCH_AE_DIA_Gorax_KDFM_BUY_4_2 = "PATCH_AE_DIA_Gorax_KDFM_BUY_4_2_DE";

    // ------
    // Greg
    // ------

    Patch_AE_DIA_Addon_Greg_RavenDead_ARMOREXPANSION_desc = "Wie wäre es mit etwas besserer Rüstung?";
    // AI_Output(other, self, "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_15_00_DE"); //Wie wäre es mit etwas besserer Rüstung?
    // AI_Output(self, other, "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_01_DE"); //Was zum Teufel denken Sie sich dabei?
    // AI_Output(self, other, "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_02_DE"); //Du tötest Raven und bist plötzlich der neue Kapitän?
    // AI_Output(other, self, "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_15_03_DE"); //Das habe ich nicht gemeint. Du bist immer noch der Captain. Ich frage nur nach einer besseren Rüstung.
    // AI_Output(self, other, "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_04_DE"); //Na gut, ich kann Ihnen eines meiner persönlichen Stücke verkaufen.
    // AI_Output(self, other, "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_05_DE"); //Aber es wird dich etwas kosten. Ich will 2700 Gold dafür.
    Patch_AE_DIA_Addon_Greg_RavenDead_ARMOREXPANSION_entry = "Ich kann für 2700 Gold von Greg einen Kapitäns Mantel kaufen.";

    Patch_AE_DIA_Addon_Greg_BUY_ARMOREXPANSION_desc = "Kapitäns Mantel kaufen (2700 Gold)";
    // AI_Output(other, self, "PATCH_AE_DIA_ADDON_GREG_BUY_ARMOREXPANSION_4_1_DE"); //Verkaufen Sie mir die Kapitäns-Rüstung.
    // AI_Output(self, other, "PATCH_AE_DIA_ADDON_GREG_BUY_ARMOREXPANSION_4_2_DE"); //Bitte sehr, aber denken Sie daran, dass ich immer noch der Kapitän bin.
    // AI_Output(self, other, "PATCH_AE_DIA_ADDON_GREG_BUY_ARMOREXPANSION_4_3_DE"); //Kommen Sie wieder, wenn Sie genug Gold haben.

    // Localized OU (do not change)
    PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_15_00 = "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_15_00_DE";
    PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_01 = "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_01_DE";
    PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_02 = "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_02_DE";
    PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_15_03 = "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_15_03_DE";
    PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_04 = "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_04_DE";
    PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_05 = "PATCH_AE_DIA_ADDON_GREG_RAVENDEAD_ARMOREXPANSION_01_05_DE";
    PATCH_AE_DIA_ADDON_GREG_BUY_ARMOREXPANSION_4_1 = "PATCH_AE_DIA_ADDON_GREG_BUY_ARMOREXPANSION_4_1_DE";
    PATCH_AE_DIA_ADDON_GREG_BUY_ARMOREXPANSION_4_2 = "PATCH_AE_DIA_ADDON_GREG_BUY_ARMOREXPANSION_4_2_DE";
    PATCH_AE_DIA_ADDON_GREG_BUY_ARMOREXPANSION_4_3 = "PATCH_AE_DIA_ADDON_GREG_BUY_ARMOREXPANSION_4_3_DE";

    // ------
    // Hagen
    // ------

    Patch_AE_DIA_Lord_Hagen_CROSSBOW_desc = "Hast du keine leichtere Rüstung für mich? (Ritterrüstung ersetzen)";
    // AI_Output(other, self, "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_01_DE"); //Hast du keine leichtere Rüstung für mich?
    // AI_Output(other, self, "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_02_DE"); //Ich ziehe es vor, Fernkampfwaffen zu benutzen.
    // AI_Output(self, other, "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_13_03_DE"); //Ich kann die Rüstung eures Ritters durch eine leichtere Version für unsere Armbrustschützen ersetzen.
    // AI_Output(other, self, "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_04_DE"); //Ich nehme es an.
    // AI_Output(self, other, "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_9_DE"); //Tragt es mit Ehre, Ritter.

    Patch_AE_DIA_Lord_Hagen_HEAVYCROSSBOW_desc = "Ich brauche eine bessere Rüstung.";
    // AI_Output(other, self, "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_15_01_DE"); //Ich brauche eine bessere Rüstung.
    // AI_Output(self, other, "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_13_03_DE"); //Hm, es stimmt, du hast dich um die Drachen im Tal der Minental.
    // AI_Output(self, other, "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_13_04_DE"); //Du hast die schwere Armbrustschützen-Rüstung verdient, hier ist sie.
    // AI_Output(other, self, "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_15_05_DE"); //Danke.
    // AI_Output(self, other, "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_15_06_DE"); //Seien Sie stolz darauf, nicht viele haben die Möglichkeit, ihn zu tragen.


    // Localized OU (do not change)
    PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_01 = "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_01_DE";
    PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_02 = "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_02_DE";
    PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_13_03 = "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_13_03_DE";
    PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_04 = "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_04_DE";
    PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_9 = "PATCH_AE_DIA_LORD_HAGEN_CROSSBOW_15_9_DE";
    PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_15_01 = "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_15_01_DE";
    PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_13_03 = "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_13_03_DE";
    PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_13_04 = "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_13_04_DE";
    PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_15_05 = "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_15_05_DE";
    PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_15_06 = "PATCH_AE_DIA_LORD_HAGEN_HEAVYCROSSBOW_15_06_DE";

    // ------
    // Harad
    // ------

    Patch_AE_DIA_HARAD_PAL_SHOW_desc = "Kannst du diese rostige Paladinrüstung für mich reparieren?";
    // AI_Output(other, self, "PATCH_AE_DIA_HARAD_PAL_SHOW_4_1_DE"); //Kannst du diese rostige Paladinrüstung für mich reparieren?
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PAL_SHOW_3_01_DE"); //Lassen Sie mich sehen.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PAL_SHOW_3_02_DE"); //Es ist lange her, dass ich so eine Rüstung gesehen habe.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PAL_SHOW_3_03_DE"); //Sie werden aus einer anderen Legierung aus Stahl und magischem Erz geschmiedet als die anderen und dann von den Magiern des Klosters in Nordmar gesegnet.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PAL_SHOW_3_04_DE"); //Der Rost ist nicht sehr tief eingedrungen, es wird nicht allzu schwierig sein, ihn zu reparieren.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PAL_SHOW_3_05_DE"); //Wenn ich die Materialien habe, natürlich.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PAL_SHOW_3_06_DE"); //Woher haben Sie es?
    // AI_Output(other, self, "PATCH_AE_DIA_HARAD_PAL_SHOW_3_07_DE"); //Martin hat es mir verkauft, es lag bei den Paladin-Vorräten herum und ich wollte es benutzen.
    Patch_AE_DIA_HARAD_PAL_SHOW_entry = "Harad wird die Rüstung für mich reparieren.";

    Patch_AE_DIA_HARAD_PALADIN_REFORGE_desc = "Was brauchst du zum reparieren der Rüstung?";
    // AI_Output(other, self, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_01_DE"); //Was brauchst du also, um die Rüstung zu reparieren?
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_02_DE"); //Hmm, lass mich nachdenken.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_04_DE"); //Ein paar rohe Stahlknüppel, sechs sollten ausreichen.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_05_DE"); //3 Stücke magischen Erzes.
    // AI_Output(other, self, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_06_DE"); //Was schulde ich Ihnen für Ihre Arbeit?
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_07_DE"); //Nichts. Es wäre mir eine Ehre, an einer solchen Rüstung zu arbeiten.
    // AI_Output(other, self, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_08_DE"); //In Ordnung, ich werde versuchen, alles zu besorgen, was Sie brauchen.
    Patch_AE_DIA_HARAD_PALADIN_REFORGE_entry1 = "Um die Rüstung zu reparieren braucht Harad sechs Stück Rohstahl und drei Erzbrocken.";
    // AI_Output(other, self, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_9_DE");//Hier ist die Rüstung.
    // AI_Output(other, self, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_10_DE"); //Und hier sind die Materialien.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_11_DE"); //In Ordnung, ich mache mich an die Arbeit.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_12_DE"); //Erledigt.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_13_DE"); //Hier ist er, ich habe ihn repariert.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_14_DE"); //Aber ich konnte die magischen Kräfte der Rüstung nicht wiederherstellen.
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_15_DE"); //Dazu brauchst du einen erfahrenen Feuermagier, der die Rüstung für dich weiht.
    // AI_Output(other, self, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_14_DE"); //Danke.
    Patch_AE_DIA_HARAD_PALADIN_REFORGE_entry2 = "Harad hat die Paladinrüstung repariert, konnte aber dessen magische Kräfte nicht wiederherstellen. Dazu werde ich wohl einen Feuermagier finden müssen.";
    // AI_Output(self, other, "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_16_DE"); //Kommen Sie wieder, wenn Sie alles haben.

    // Localized OU (do not change)
    PATCH_AE_DIA_HARAD_PAL_SHOW_4_1 = "PATCH_AE_DIA_HARAD_PAL_SHOW_4_1_DE";
    PATCH_AE_DIA_HARAD_PAL_SHOW_3_01 = "PATCH_AE_DIA_HARAD_PAL_SHOW_3_01_DE";
    PATCH_AE_DIA_HARAD_PAL_SHOW_3_02 = "PATCH_AE_DIA_HARAD_PAL_SHOW_3_02_DE";
    PATCH_AE_DIA_HARAD_PAL_SHOW_3_03 = "PATCH_AE_DIA_HARAD_PAL_SHOW_3_03_DE";
    PATCH_AE_DIA_HARAD_PAL_SHOW_3_04 = "PATCH_AE_DIA_HARAD_PAL_SHOW_3_04_DE";
    PATCH_AE_DIA_HARAD_PAL_SHOW_3_05 = "PATCH_AE_DIA_HARAD_PAL_SHOW_3_05_DE";
    PATCH_AE_DIA_HARAD_PAL_SHOW_3_06 = "PATCH_AE_DIA_HARAD_PAL_SHOW_3_06_DE";
    PATCH_AE_DIA_HARAD_PAL_SHOW_3_07 = "PATCH_AE_DIA_HARAD_PAL_SHOW_3_07_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_01 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_01_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_02 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_02_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_04 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_04_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_05 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_05_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_06 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_06_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_07 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_07_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_08 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_08_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_9 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_9_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_10 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_10_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_11 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_11_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_12 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_12_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_13 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_13_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_14 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_14_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_15 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_15_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_14 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_15_14_DE";
    PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_16 = "PATCH_AE_DIA_HARAD_PALADIN_REFORGE_13_16_DE";
    PATCH_AE_DIA_HARAD_end_MAKE_1 = "PATCH_AE_DIA_HARAD_end_MAKE_1_DE";
    PATCH_AE_DIA_HARAD_end_MAKE_2 = "PATCH_AE_DIA_HARAD_end_MAKE_2_DE";
    PATCH_AE_DIA_HARAD_end_MAKE_3 = "PATCH_AE_DIA_HARAD_end_MAKE_3_DE";
    PATCH_AE_DIA_HARAD_end_MAKE_4 = "PATCH_AE_DIA_HARAD_end_MAKE_4_DE";
    PATCH_AE_DIA_HARAD_end_MAKE_5 = "PATCH_AE_DIA_HARAD_end_MAKE_5_DE";
    PATCH_AE_DIA_HARAD_end_MAKE_6 = "PATCH_AE_DIA_HARAD_end_MAKE_6_DE";
    PATCH_AE_DIA_HARAD_end_MAKE_7 = "PATCH_AE_DIA_HARAD_end_MAKE_7_DE";
    PATCH_AE_DIA_HARAD_end_MAKE_8 = "PATCH_AE_DIA_HARAD_end_MAKE_8_DE";
    PATCH_AE_DIA_HARAD_end_MAKE_9 = "PATCH_AE_DIA_HARAD_end_MAKE_9_DE";

    // ------
    // Huno
    // ------

    Patch_AE_DIA_HUNO_PAL_REFORGE_desc = "Kannst du diese rostige Paladinrüstung für mich reparieren?";
    // AI_Output(other, self, "PATCH_AE_DIA_HUNO_PAL_REFORGE_4_1_DE"); //Kannst du diese rostige Paladinrüstung für mich reparieren?
    // AI_Output(self, other, "PATCH_AE_DIA_HUNO_PAL_REFORGE_3_01_DE"); //Ich habe absolut keine Erfahrung mit Paladin-Rüstungen. Im Tal der Minental gab es nichts dergleichen.
    // AI_Output(self, other, "PATCH_AE_DIA_HUNO_PAL_REFORGE_3_02_DE"); //Es tut mir leid, aber ich kann Ihnen in dieser Sache nicht helfen.
    // AI_Output(self, other, "PATCH_AE_DIA_HUNO_PAL_REFORGE_3_03_DE"); //Ihr müsst einen anderen Schmied finden.
    Patch_AE_DIA_HUNO_PAL_REFORGE_entry = "Huno wird meine Rüstung nicht reparieren.";

    // Localized OU (do not change)
    PATCH_AE_DIA_HUNO_PAL_REFORGE_4_1 = "PATCH_AE_DIA_HUNO_PAL_REFORGE_4_1_DE";
    PATCH_AE_DIA_HUNO_PAL_REFORGE_3_01 = "PATCH_AE_DIA_HUNO_PAL_REFORGE_3_01_DE";
    PATCH_AE_DIA_HUNO_PAL_REFORGE_3_02 = "PATCH_AE_DIA_HUNO_PAL_REFORGE_3_02_DE";
    PATCH_AE_DIA_HUNO_PAL_REFORGE_3_03 = "PATCH_AE_DIA_HUNO_PAL_REFORGE_3_03_DE";

    // ------
    // Jan
    // ------

    Patch_AE_DIA_JAN_PAL_REFORGE_desc = "Kannst du diese rostige Paladinrüstung für mich reparieren?";
    // AI_Output(other, self, "PATCH_AE_DIA_JAN_PAL_REFORGE_4_1_DE"); //Kannst du diese rostige Paladinrüstung für mich reparieren?
    // AI_Output(self, other, "PATCH_AE_DIA_JAN_PAL_REFORGE_3_01_DE"); //Ich bewege mich auf dünnem Eis, nur um hier arbeiten zu dürfen.
    // AI_Output(self, other, "PATCH_AE_DIA_JAN_PAL_REFORGE_3_02_DE"); //Ich werde nicht riskieren, dass mich einer Ihrer Kollegen anzeigt, weil ich in den Vorräten der Paladins gewühlt habe.
    // AI_Output(self, other, "PATCH_AE_DIA_JAN_PAL_REFORGE_3_03_DE"); //Ihr müsst einen anderen Schmied finden.
    Patch_AE_DIA_JAN_PAL_REFORGE_entry = "Jan wird meine Rüstung nicht reparieren.";

    // Localized OU (do not change)
    PATCH_AE_DIA_JAN_PAL_REFORGE_4_1 = "PATCH_AE_DIA_JAN_PAL_REFORGE_4_1_DE";
    PATCH_AE_DIA_JAN_PAL_REFORGE_3_01 = "PATCH_AE_DIA_JAN_PAL_REFORGE_3_01_DE";
    PATCH_AE_DIA_JAN_PAL_REFORGE_3_02 = "PATCH_AE_DIA_JAN_PAL_REFORGE_3_02_DE";
    PATCH_AE_DIA_JAN_PAL_REFORGE_3_03 = "PATCH_AE_DIA_JAN_PAL_REFORGE_3_03_DE";

    // ------
    // Lee
    // ------

    Patch_AE_DIA_LEE_SLD_SCOUTArmor_desc = "Gibt es auch eine leichtere Rüstung?";
    // AI_Output(other, self, "PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_15_01_DE"); //Gibt es auch eine leichtere Rüstung?
    // AI_Output(other, self, "PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_15_02_DE"); //Ich ziehe es vor, Abstand zu halten.
    // AI_Output(self, other, "PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_13_03_DE"); //Ich habe nichts dergleichen für Sie, aber Sie sind nicht der erste, der um so etwas bittet.
    // AI_Output(self, other, "PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_13_04_DE"); //Geh zu Wolf. Ich denke, er sollte etwas für dich haben.

    // Localized OU (do not change)
    PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_15_01 = "PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_15_01_DE";
    PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_15_02 = "PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_15_02_DE";
    PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_13_03 = "PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_13_03_DE";
    PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_13_04 = "PATCH_AE_DIA_LEE_SLD_SCOUTARMOR_13_04_DE";

    // ------
    // Martin
    // ------

    Patch_AE_TOPIC_MARTIN_ARMOR = "Einzigartige Paladinrüstung";

    // AI_Output(self, other, "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_01_DE"); //Ich habe gehört, dass du ein Paladin geworden bist.
    // AI_Output(self, other, "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_02_DE"); //Ich habe vielleicht etwas Besonderes für Sie
    // AI_Output(other, self, "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_03_DE"); //Wovon sprechen Sie?
    // AI_Output(self, other, "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_04_DE"); //Ich habe hier einige außergewöhnliche Paladin-Rüstungen auf Lager.
    // AI_Output(self, other, "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_05_DE"); //Ich habe gehört, dass diese Art von Rüstung einen hohen Schutz gegen magische Angriffe bietet und gleichzeitig die eigenen magischen Fähigkeiten des Trägers erhöht.
    // AI_Output(self, other, "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_06_DE"); //Aber es liegt schon eine Weile herum, und das Wetter an der Küste hat ihm nicht gut getan.
    // AI_Output(self, other, "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_07_DE"); //Es ist nichts, was nicht repariert werden kann. Dir wird schon etwas einfallen.
    // AI_Output(self, other, "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_08_DE"); //Für 2000 Gold gehört er Ihnen.
    PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_entry = "Martin hat mir angeboten mir für 2000 Gold eine einzigartige Paladinrüstung zu verkaufen. Hört sich interesant an.";

    Patch_AE_DIA_Martin_ARKPALA_BUY_desc = "Ok, Ich will die Rüstung. (2000 Gold).";
    // AI_Output(other, self, "PATCH_AE_DIA_MARTIN_ARKPALA_BUY_4_1_DE"); //Ok, Ich will die Rüstung.
    // AI_Output(self, other, "PATCH_AE_DIA_MARTIN_ARKPALA_BUY_4_2_DE"); //Also gut, hier ist es.
    // AI_Output(self, other, "PATCH_AE_DIA_MARTIN_ARKPALA_BUY_4_3_DE"); //Komm wieder, wenn du genug Gold bei dir hast
    Patch_AE_DIA_Martin_ARKPALA_BUY_entry = "Ich habe die Paladinrüstung von Martin gekauft. Sie ist verrosten aber ein guter Schmied kann sie vermutlich reparieren. Ich muss nur einen finden.";

    // Localized OU (do not change)
    PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_01 = "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_01_DE";
    PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_02 = "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_02_DE";
    PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_03 = "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_03_DE";
    PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_04 = "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_04_DE";
    PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_05 = "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_05_DE";
    PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_06 = "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_06_DE";
    PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_07 = "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_07_DE";
    PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_08 = "PATCH_AE_DIA_MARTIN_ARCPALA_NOTIF_3_08_DE";
    PATCH_AE_DIA_MARTIN_ARKPALA_BUY_4_1 = "PATCH_AE_DIA_MARTIN_ARKPALA_BUY_4_1_DE";
    PATCH_AE_DIA_MARTIN_ARKPALA_BUY_4_2 = "PATCH_AE_DIA_MARTIN_ARKPALA_BUY_4_2_DE";
    PATCH_AE_DIA_MARTIN_ARKPALA_BUY_4_3 = "PATCH_AE_DIA_MARTIN_ARKPALA_BUY_4_3_DE";

    // ------
    // Matteo
    // ------

    Patch_AE_DIA_Matteo_GAMBESON_desc = "Jäger Stoffrüstung kaufen. (350 Gold).";
    // AI_Output(other, self, "PATCH_AE_DIA_MATTEO_GAMBESON_15_00_DE"); //Okay, gib mir die Rüstung.
    // AI_Output(self, other, "PATCH_AE_DIA_MATTEO_GAMBESON_09_01_DE"); //Es wird Ihnen gefallen.
    // AI_Output(self, other, "PATCH_AE_DIA_MATTEO_GAMBESON_09_02_DE"); //Die Rüstung ist ihr Gewicht in Gold wert, also komm wieder, wenn du genug hast.

    // Localized OU (do not change)
    PATCH_AE_DIA_MATTEO_GAMBESON_15_00 = "PATCH_AE_DIA_MATTEO_GAMBESON_15_00_DE";
    PATCH_AE_DIA_MATTEO_GAMBESON_09_01 = "PATCH_AE_DIA_MATTEO_GAMBESON_09_01_DE";
    PATCH_AE_DIA_MATTEO_GAMBESON_09_02 = "PATCH_AE_DIA_MATTEO_GAMBESON_09_02_DE";

    // ------
    // Milten
    // ------

    Patch_AE_DIA_MILTEN_PALADINARMOR_desc = "Ich brauche deine Hilfe.";
    // AI_Output(other, self, "PATCH_AE_DIA_MILTEN_PALADINARMOR_15_01_DE"); //Ich brauche deine Hilfe.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_02_DE"); //Was ist los?
    // AI_Output(other, self, "PATCH_AE_DIA_MILTEN_PALADINARMOR_04_DE"); //Ich muss die magischen Kräfte dieser Rüstung wiederherstellen, könnten Sie das für mich tun?
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_05_DE"); //Zeigen Sie es mir.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_06_DE"); //Wow, das habe ich nicht erwartet.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_07_DE"); //Diese Art von Rüstung wird von den Paladinen aus Myrtana mitgenommen, um im Kloster in Nordmar gesegnet zu werden.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_08_DE"); //Ich habe ein wenig über das Segnungsritual gehört, aber ich habe noch nicht genug Wissen, um es durchzuführen.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_09_DE"); //Wenn ich mich nicht irre, gibt es in der Bibliothek des Klosters ein Buch, in dem dieser Vorgang beschrieben wird.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_10_DE"); //Ich werde etwas Zeit brauchen, um das Buch zu studieren. In der Zwischenzeit solltest du dich um die Drachen im der Minental kümmern, du weißt, dass Garonds Einheit nicht lange überleben wird.
    // AI_Output(other, self, "PATCH_AE_DIA_MILTEN_PALADINARMOR_15_11_DE"); //Ja, wir sehen uns später, Milten.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_12_DE"); //Viel Glück!
    Patch_AE_DIA_MILTEN_PALADINARMOR_entry = "Milten wird versuchen die magischen Kräfte der Rüstung wiederherzustellen. Zuerst muss er aber einige Nachforschungen betreiben. Das wird etwas dauern. Ich sollte mich in der Zwischenzeit um die Drachen kümmern.";

    Patch_AE_DIA_MILTEN_PLATEARMOR_desc = "Hast du bei deinen Nachforschungen Fortschritte gemacht?";
    // AI_Output(other, self, "PATCH_AE_DIA_MILTEN_PLATEARMOR_15_01_DE"); //Hast du bei deinen Nachforschungen Fortschritte gemacht?
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_02_DE"); //Ja, ich kann sagen, dass ich den rituellen Prozess verstehe.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_03_DE"); //Aber ich werde ein paar Dinge brauchen.
    // AI_Output(other, self, "PATCH_AE_DIA_MILTEN_PLATEARMOR_15_04_DE"); //Was werden Sie brauchen?
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_05_DE"); //Eine Schriftrolle der Zerstörung des Bösen, ein Feuerball und zwei Bergkristalle.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_06_DE"); //Nur so kann ich ähnliche Ergebnisse wie bei einem Ritual im Kloster Nordmar erzielen.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_07_DE"); //Okay, ich werde die Sachen holen gehen.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_08_DE"); //Viel Glück, ich hoffe, Sie haben Erfolg.
    Patch_AE_DIA_MILTEN_PLATEARMOR_entry = "Um die Rüstung zu stärken braucht Milten eine Schriftrolle Böses vernichten, eine Schriftrolle Feuerball und zwei Bergkristalle.";

    Patch_AE_DIA_MILTEN_RITUALARMOR_desc = "Ich habe alles was du brauchst.";
    // AI_Output(other, self, "PATCH_AE_DIA_MILTEN_RITUALARMOR_15_01_DE"); //Ich habe alles was du brauchst.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_RITUALARMOR_13_02_DE"); //Oh, großartig. Ich kann mit dem Ritual beginnen.
    Patch_AE_DIA_MILTEN_RITUALARMOR_entry = "Ich habe Milten alles gebracht, was er für das Ritual braucht.";

    Patch_AE_DIA_MILTEN_LORDRMOR_desc = "Toll, wann ist das Ritual vollendet?";
    // AI_Output(other, self, "PATCH_AE_DIA_MILTEN_LORDRMOR_15_00_DE"); //Toll, wann ist das Ritual vollendet?
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_LORDRMOR_08_01_DE"); //Es wird eine Weile dauern. Kommen Sie morgen wieder.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_LORDRMOR_08_02_DE"); //Ich habe es bereits getan, es war ein Erfolg.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_LORDRMOR_08_03_DE"); //Alles verlief erstaunlich reibungslos.
    // AI_Output(other, self, "PATCH_AE_DIA_MILTEN_LORDRMOR_15_04_DE"); //Das macht mich froh. Ich danke Ihnen vielmals.
    // AI_Output(self, other, "PATCH_AE_DIA_MILTEN_LORDRMOR_08_05_DE"); //Gern geschehen. Möge die Rüstung Ihnen gute Dienste leisten.
    // AI_Output(self, other, "PATCH_AE_DIA_WOLFEE_ARMORREADY_08_06_DE"); //NN
    Patch_AE_DIA_MILTEN_LORDRMOR_entry = "Milten hat es geschafft die magischen Kräfte der Rüstung wiederherzustellen.";

    // Localized OU (do not change)
    PATCH_AE_DIA_MILTEN_PALADINARMOR_15_01 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_15_01_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_13_02 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_02_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_04 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_04_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_13_05 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_05_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_13_06 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_06_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_13_07 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_07_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_13_08 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_08_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_13_09 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_09_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_13_10 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_10_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_15_11 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_15_11_DE";
    PATCH_AE_DIA_MILTEN_PALADINARMOR_13_12 = "PATCH_AE_DIA_MILTEN_PALADINARMOR_13_12_DE";
    PATCH_AE_DIA_MILTEN_PLATEARMOR_15_01 = "PATCH_AE_DIA_MILTEN_PLATEARMOR_15_01_DE";
    PATCH_AE_DIA_MILTEN_PLATEARMOR_13_02 = "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_02_DE";
    PATCH_AE_DIA_MILTEN_PLATEARMOR_13_03 = "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_03_DE";
    PATCH_AE_DIA_MILTEN_PLATEARMOR_15_04 = "PATCH_AE_DIA_MILTEN_PLATEARMOR_15_04_DE";
    PATCH_AE_DIA_MILTEN_PLATEARMOR_13_05 = "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_05_DE";
    PATCH_AE_DIA_MILTEN_PLATEARMOR_13_06 = "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_06_DE";
    PATCH_AE_DIA_MILTEN_PLATEARMOR_13_07 = "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_07_DE";
    PATCH_AE_DIA_MILTEN_PLATEARMOR_13_08 = "PATCH_AE_DIA_MILTEN_PLATEARMOR_13_08_DE";
    PATCH_AE_DIA_MILTEN_RITUALARMOR_15_01 = "PATCH_AE_DIA_MILTEN_RITUALARMOR_15_01_DE";
    PATCH_AE_DIA_MILTEN_RITUALARMOR_13_02 = "PATCH_AE_DIA_MILTEN_RITUALARMOR_13_02_DE";
    PATCH_AE_DIA_MILTEN_LORDRMOR_15_00 = "PATCH_AE_DIA_MILTEN_LORDRMOR_15_00_DE";
    PATCH_AE_DIA_MILTEN_LORDRMOR_08_01 = "PATCH_AE_DIA_MILTEN_LORDRMOR_08_01_DE";
    PATCH_AE_DIA_MILTEN_LORDRMOR_08_02 = "PATCH_AE_DIA_MILTEN_LORDRMOR_08_02_DE";
    PATCH_AE_DIA_MILTEN_LORDRMOR_08_03 = "PATCH_AE_DIA_MILTEN_LORDRMOR_08_03_DE";
    PATCH_AE_DIA_MILTEN_LORDRMOR_15_04 = "PATCH_AE_DIA_MILTEN_LORDRMOR_15_04_DE";
    PATCH_AE_DIA_MILTEN_LORDRMOR_08_05 = "PATCH_AE_DIA_MILTEN_LORDRMOR_08_05_DE";
    PATCH_AE_DIA_WOLFEE_ARMORREADY_08_06 = "PATCH_AE_DIA_WOLFEE_ARMORREADY_08_06_DE";

    // ------
    // Mortis
    // ------

    Patch_AE_TOPIC_MORTIS_ARMOR = "Milizrüstung-Verbesserungen";

    PATCH_AE_DIA_MORTIS_ARMORQUESTION_desc = "Hast du keine bessere Rüstung für mich?";
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_ARMORQUESTION_15_01_DE"); //Hast du keine bessere Rüstung für mich?
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_02_DE"); //Nur Lord Andre kann dir eine bessere Rüstung geben.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_03_DE"); //Das heißt aber nicht, dass ich das, was Sie bereits haben, nicht noch verbessern kann. Du wärst nicht die erste Person, für die ich etwas getan habe.
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_ARMORQUESTION_15_04_DE"); //Was wird es kosten?
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_05_DE"); //Ihr müsst euer eigenes Material mitbringen, ich habe keins mehr übrig.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_06_DE"); //Und bringt auch etwas Gold als Bezahlung für meine Arbeit mit.
    PATCH_AE_DIA_MORTIS_ARMORQUESTION_entry = "Mortis kann meine Milizrüstung verbesseren, wenn ich ihm Gold und Materialien bringe.";

    PATCH_AE_DIA_MORTIS_MIL_LTHINGS_desc = "Ich will meine leichte Rüstung verbessern.";
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_15_01_DE"); //Ich will meine leichte Rüstung verbessern.
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_15_04_DE"); //Was brauchen Sie dafür?
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_13_06_DE"); //Für eine leichte Rüstung reichen ein roher Stahl und ein Wildschweinfell aus.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_13_07_DE"); //Und sagen wir mal, 200 Gold sind genug für mich.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_13_08_DE"); //Und natürlich müsst ihr mir die Rüstung bringen.
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_15_09_DE"); //In Ordnung, ich werde versuchen, es zu bekommen.
    PATCH_AE_DIA_MORTIS_MIL_LTHINGS_entry = "Um meine leichte Rüstung zu verbessern braucht Mortis ein Stück Rohstahl, ein Keilerfell und 200 Gold.";

    PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_desc = "Ich habe alle Materialien um meine leichte Rüstung zu verbessern.";
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_15_01_DE"); //Ich habe alle Materialien um meine leichte Rüstung zu verbessern.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_12_DE"); //In Ordnung, ich mache mich an die Arbeit.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_13_DE"); //Erledigt.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_14_DE"); //Bitte sehr, ich denke, ich habe gute Arbeit geleistet.
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_15_15_DE"); //Danke.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_16_DE"); //Kommen Sie wieder, wenn Sie alles dabei haben.
    PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_entry = "Mortis hat meine leichte Rüstung verbessert.";

    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_desc = "Ich will meine mittlere Rüstung verbessern.";
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_15_01_DE"); //Ich will meine mittlere Rüstung verbessern.
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_15_03_DE"); //Was brauchen Sie dafür?
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_13_04_DE"); //Für die mittlere Rüstung müssen Sie etwas mehr mitbringen als beim letzten Mal.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_13_05_DE"); //zwei rohe Stahlknüppel und eine Warg-Haut.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_13_06_DE"); //Ich berechne dir 600 Gold für den Auftrag.
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_15_08_DE"); //In Ordnung, ich werde versuchen, es zu bekommen.
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_entry = "Um meine leichte Rüstung zu verbessern braucht Mortis zwei Stück Rohstahl, ein Wargfell und 600 Gold.";

    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_desc = "Ich habe alle Materialien um meine mittlere Rüstung zu verbessern.";
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_15_01_DE"); //Ich habe alle Materialien um meine mittlere Rüstung zu verbessern.
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_15_10_DE"); //Hier ist es.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_11_DE"); //In Ordnung, ich mache mich an die Arbeit.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_12_DE"); //Erledigt.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_13_DE"); //Bitte sehr, ich denke, ich habe gute Arbeit geleistet.
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_15_14_DE"); //Danke.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_16_DE"); //Kommen Sie wieder, wenn Sie alles dabei haben.
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_entry = "Mortis hat meine mittlere Rüstung verbessert.";

    PATCH_AE_DIA_MORTIS_PAL_REFORGE_desc = "Kannst du diese rostige Paladinrüstung für mich reparieren?";
    // AI_Output(other, self, "PATCH_AE_DIA_MORTIS_PAL_REFORGE_4_1_DE"); //Kannst du diese rostige Paladinrüstung für mich reparieren?
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_PAL_REFORGE_3_01_DE"); //Nein, ich habe weder die Zeit noch die Fähigkeit dazu.
    // AI_Output(self, other, "PATCH_AE_DIA_MORTIS_PAL_REFORGE_3_02_DE"); //Ihr müsst einen anderen Schmied finden.
    PATCH_AE_DIA_MORTIS_PAL_REFORGE_entry = "Mortis wird meine Rüstung nicht reparieren.";

    // Localized OU (do not change)
    PATCH_AE_DIA_MORTIS_ARMORQUESTION_15_01 = "PATCH_AE_DIA_MORTIS_ARMORQUESTION_15_01_DE";
    PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_02 = "PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_02_DE";
    PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_03 = "PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_03_DE";
    PATCH_AE_DIA_MORTIS_ARMORQUESTION_15_04 = "PATCH_AE_DIA_MORTIS_ARMORQUESTION_15_04_DE";
    PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_05 = "PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_05_DE";
    PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_06 = "PATCH_AE_DIA_MORTIS_ARMORQUESTION_13_06_DE";
    PATCH_AE_DIA_MORTIS_MIL_LTHINGS_15_01 = "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_15_01_DE";
    PATCH_AE_DIA_MORTIS_MIL_LTHINGS_15_04 = "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_15_04_DE";
    PATCH_AE_DIA_MORTIS_MIL_LTHINGS_13_06 = "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_13_06_DE";
    PATCH_AE_DIA_MORTIS_MIL_LTHINGS_13_07 = "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_13_07_DE";
    PATCH_AE_DIA_MORTIS_MIL_LTHINGS_13_08 = "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_13_08_DE";
    PATCH_AE_DIA_MORTIS_MIL_LTHINGS_15_09 = "PATCH_AE_DIA_MORTIS_MIL_LTHINGS_15_09_DE";
    PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_15_01 = "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_15_01_DE";
    PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_12 = "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_12_DE";
    PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_13 = "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_13_DE";
    PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_14 = "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_14_DE";
    PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_15_15 = "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_15_15_DE";
    PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_16 = "PATCH_AE_DIA_MORTIS_MIL_LREFORGEDARMOR_13_16_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_15_01 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_15_01_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_15_03 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_15_03_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_13_04 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_13_04_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_13_05 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_13_05_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_13_06 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_13_06_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_15_08 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMHUH_15_08_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_15_01 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_15_01_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_15_10 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_15_10_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_11 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_11_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_12 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_12_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_13 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_13_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_15_14 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_15_14_DE";
    PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_16 = "PATCH_AE_DIA_MORTIS_MILITIA_MEDIUMARMOR_13_16_DE";
    PATCH_AE_DIA_MORTIS_PAL_REFORGE_4_1 = "PATCH_AE_DIA_MORTIS_PAL_REFORGE_4_1_DE";
    PATCH_AE_DIA_MORTIS_PAL_REFORGE_3_01 = "PATCH_AE_DIA_MORTIS_PAL_REFORGE_3_01_DE";
    PATCH_AE_DIA_MORTIS_PAL_REFORGE_3_02 = "PATCH_AE_DIA_MORTIS_PAL_REFORGE_3_02_DE";

    // ----
    // Hero
    // ----

    Patch_AE_PC_FORGE_ARMOR_desc = "Rüstung schmieden";
    Patch_AE_PC_ITAR_PAL_ST_desc = "Stewark Plattenrüstung schmieden";
    Patch_AE_PC_ITAR_PAL_ANH_desc = "Den Helm der Angereicherten Paladinrüstung entfernen";
    Patch_AE_PC_ITAR_PAL_AFH_desc = "Das Visier der Angereicherten Paladinrüstung herunterziehen";
    Patch_AE_PC_ITAR_PAL_AFH_NH_desc = "Das Visier der Angereicherten Paladinrüstung herunterziehen";
    Patch_AE_PC_ITAR_PAL_ANH_FH_desc = "Den Helm der Angereicherten Paladinrüstung entfernen";
    Patch_AE_PC_ITAR_PAL_A_FH_desc = "Das Visier der Angereicherten Paladinrüstung hochziehen";
    Patch_AE_PC_ITAR_PAL_A_NH_desc = "Das Visier der Angereicherten Paladinrüstung hochziehen";
    Patch_AE_PC_ITAR_PAL_FNH_desc = "Den Helm der Reparierten Paladinrüstung entfernen";
    Patch_AE_PC_ITAR_PAL_FFH_desc = "Das Visier der Reparierten Paladinrüstung herunterziehen";
    Patch_AE_PC_ITAR_PAL_FFH_NH_desc = "Das Visier der Reparierten Paladinrüstung herunterziehen";
    Patch_AE_PC_ITAR_PAL_fNH_FH_desc = "Den Helm der Reparierten Paladinrüstung entfernen";
    Patch_AE_PC_ITAR_PAL_F_FH_desc = "Das Visier der Reparierten Paladinrüstung hochziehen";
    Patch_AE_PC_ITAR_PAL_F_NH_desc = "Das Visier der Angereicherten Paladinrüstung hochziehen";
    Patch_AE_PC_ITAR_PAL_RNH_desc = "Den Helm der Rostigen Paladinrüstung entfernen";
    Patch_AE_PC_ITAR_PAL_RFH_desc = "Das Visier der Rostigen Paladinrüstung herunterziehen";
    Patch_AE_PC_ITAR_PAL_RFH_NH_desc = "Das Visier der Rostigen Paladinrüstung herunterziehen";
    Patch_AE_PC_ITAR_PAL_RNH_FH_desc = "Den Helm der Rostigen Paladinrüstung entfernen";
    Patch_AE_PC_ITAR_PAL_R_FH_desc = "Das Visier der Rostigen Paladinrüstung hochziehen";
    Patch_AE_PC_ITAR_PAL_R_NH_desc = "Das Visier der Rostigen Paladinrüstung hochziehen";
    Patch_AE_PC_ITAR_CRUSADER_NH_desc = "Den Helm der Kreuzritterrüstung entfernen";
    Patch_AE_PC_ITAR_nh_crusader_desc = "Einen Helm zur Kreuzritterrüstung hinzufügen";
    Patch_AE_PC_PAL_MH_desc = "Den Helm der schwere ritterrüstung entfernen";
    Patch_AE_PC_ITAR_PAL_MH_FH_desc = "Einen Helm zur schwere rüstung hinzufügen";
    Patch_AE_PC_ITAR_PAL_HNH_desc = "Den Helm der Paladinrüstung entfernen";
    Patch_AE_PC_ITAR_PAL_HFH_desc = "Das Visier der Paladinrüstung herunterziehen";
    Patch_AE_PC_ITAR_PAL_HFH_NH_desc = "Das Visier der Paladinrüstung herunterziehen";
    Patch_AE_PC_ITAR_PAL_HNH_FH_desc = "Den Helm der Paladinrüstung entfernen";
    Patch_AE_PC_Itar_pal_h_FH_desc = "Das Visier der Paladinrüstung hochziehen";
    Patch_AE_PC_Itar_pal_h_NH_desc = "Das Visier der Paladinrüstung hochziehen";
    Patch_AE_PC_Itar_djg_M_desc = "Den Helm der mittlere Drachenjägerrüstung entfernen";
    Patch_AE_PC_Itar_djg_M_NH_desc = "Den Helm der mittlere Drachenjägerrüstung hinzufügen";
    Patch_AE_PC_Itar_djg_H_NH_desc = "Den Helm der schwere Drachenjägerrüstung hinzufügen";
    Patch_AE_PC_Itar_djg_H_desc = "Den Helm der schwere Drachenjägerrüstung entfernen";

    // ------
    // Ulthar
    // ------

    PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_desc = "Ich habe alle Schreine bereinigt.";
    // AI_Output(self, other, "PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_05_01_DE"); //Warte, wir wollten dich in deinem Kampf gegen das Böse mit einer neuen Rüstung unterstützen.
    // AI_Output(self, other, "PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_05_02_DE"); //Nimm diese Rüstung des Kreuzritters von Innos, ich bin sicher, du wirst sie gebrauchen können.
    // AI_Output(other, self, "PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_05_03_DE"); //Danke.

    // Localized OU (do not change)
    PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_05_01 = "PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_05_01_DE";
    PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_05_02 = "PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_05_02_DE";
    PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_05_03 = "PATCH_AE_DIA_ARMOREXPANSION_ULTHAR_05_03_DE";

    // ----
    // Wolf
    // ----

    PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_desc = "Ich habe gehört, du machst Rüstungen.";
    // AI_Output(other, self, "PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_15_01_DE"); //Ich habe gehört, du machst Rüstungen.
    // AI_Output(self, other, "PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_15_02_DE"); //Dann hast du richtig gehört, ich mache leichtere Lederrüstungen für die Jagd.
    // AI_Output(self, other, "PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_13_03_DE"); //Zwar bieten sie keinen so guten Schutz, erleichtern jedoch das Schießen mit Bogen oder Armbrust..

    PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_desc = "Ich möchte meine Rüstung durch die leichtere ersetzen.";
    // AI_Output(other, self, "PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_15_02_DE"); //Ich möchte meine Rüstung durch die leichtere ersetzen.
    // AI_Output(self, other, "PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_13_03_DE"); //Klar, ich habe gerade eins gemacht. Bitte sehr.
    // AI_Output(other, self, "PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_15_06_DE"); //Danke.
    // AI_Output(self, other, "PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_13_07_DE"); //Sie sind herzlich willkommen.

    DIA_Wolf_ArmorM_AEXPANSION_desc = "Wie wäre es mit einer besseren Rüstung?.";
    // AI_Output(other, self, "DIA_Wolf_ArmorM_AEXPANSION_15_00_DE"); //Wie wäre es mit einer besseren Rüstung?.
    // AI_Output(self, other, "DIA_Wolf_ArmorM_AEXPANSION_04_01_DE"); //Sicher, ich kann es Ihnen jetzt verkaufen.
    // AI_Output(self, other, "DIA_Wolf_ArmorM_AEXPANSION_04_02_DE"); //Ich habe hier eine mittelschwere Rüstung für dich, es ist ein gutes Stück.
    // AI_Output(self, other, "DIA_Wolf_ArmorM_AEXPANSION_04_03_DE"); //Tut mir leid, aber Lee wollte nicht, dass ich es dir einfach so gebe. Ich denke, du solltest zuerst Torlof helfen.
    // AI_Output(self, other, "DIA_Wolf_ArmorM_AEXPANSION_04_04_DE"); //Wenn du fertig bist, komm zu mir, ich werde etwas Besseres für dich haben..

    DIA_Wolf_BuyArmorMP_AEXPANSION_desc = "Mittlere Jagdrüstung kaufen (Schutz: 45/45, +6% Bogen Bonus Preis 1000).";
    // AI_Output(other, self, "DIA_Wolf_BuyArmorMP_AEXPANSION_15_00_DE"); //Gib mir die Rüstung.
    // AI_Output(self, other, "DIA_Wolf_BuyArmorMP_AEXPANSION_04_01_DE"); //Hier, bitte sehr. Es ist ein anständiges Stück Rüstung.
    // AI_Output(self, other, "DIA_Wolf_BuyArmorMP_AEXPANSION_04_02_DE"); //Tut mir leid, aber ich kann sie dir nicht umsonst geben. Lee würde mir den Kopf abreißen, wenn er herausfände, dass ich die Rüstung umsonst verschenke.

    DIA_Wolf_ArmorBow_AEXPANSION_desc = "Hätten Sie nicht eine bessere Rüstung für mich?.";
    // AI_Output(other, self, "DIA_Wolf_ArmorBow_AEXPANSION_15_00_DE"); //Hätten Sie nicht eine bessere Rüstung für mich?.
    // AI_Output(self, other, "DIA_Wolf_ArmorBow_AEXPANSION_04_01_DE"); //Ja, sicher.

    DIA_Wolf_BuyArmorBow_AEXPANSION_desc = "Schwere Jagd-Rüstung kaufen (Schutz: 70/70, +6% Bogen Bonus, Preis 2500).";
    // AI_Output(other, self, "DIA_Wolf_BuyArmorBow_AEXPANSION_15_00_DE"); //Gib mir die Rüstung.
    // AI_Output(self, other, "DIA_Wolf_BuyArmorBow_AEXPANSION_04_01_DE"); //Hier ist er. Ein gutes Stück, ich bin stolz darauf.
    // AI_Output(self, other, "DIA_Wolf_BuyArmorBow_AEXPANSION_04_02_DE"); //Du weißt, wie das ist. Zuerst musst du mir genug Gold bringen.

    DIA_Wolf_AboutCrawler_Description_AEXPANSION = "Eigentlich würde ich es vorziehen, die Rüstung leichter zu machen.";
    // AI_Output(other, self, "DIA_Wolf_AboutCrawler_AEXPANSION_15_00_DE"); //Eigentlich würde ich es vorziehen, die Rüstung leichter zu machen.
    // AI_Output(self, other, "DIA_Wolf_AboutCrawler_AEXPANSION_08_01_DE"); //Klar, kein Problem. Bringen Sie mir einfach 7 von diesen Crawlerplatten.

    DIA_Wolf_BringPlates_Description_AEXPANSION = "Ich habe dir die Crawlerplatten für die Rüstung besorgt.";

    Patch_AE_DIA_WOLF_CRAWLERARMOR_Description = "Toll, wann wird die Rüstung fertig sein?";

    Patch_AE_TOPIC_WOLF_CRAWLERARMOR = "Crawler Platte Jagd Rüstung";
    Patch_AE_TOPIC_WOLF_CRAWLERARMOR_NOTIF_entry = "Aus 7 Crawlerplatten kann Wolf mir eine Jagd Rüstung herstellen.";
    Patch_AE_DIA_WOLF_CRAWLERARMOR_Bring_entry = "Ich habe die Crawler platten mitgebracht.";
    Patch_AE_DIA_WOLF_GOTARMOR_entry = "Wolf gab mir die Rüstung.";

    // Localized OU (do not change)
    PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_15_01 = "PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_15_01_DE";
    PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_15_02 = "PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_15_02_DE";
    PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_13_03 = "PATCH_AE_DIA_WOLF_SLD_SCOUTARMOR_13_03_DE";
    PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_15_02 = "PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_15_02_DE";
    PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_13_03 = "PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_13_03_DE";
    PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_15_06 = "PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_15_06_DE";
    PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_13_07 = "PATCH_AE_DIA_WOLF_SLD_SCOUTARMORBOUGHT_13_07_DE";
    DIA_Wolf_ArmorM_AEXPANSION_15_00 = "DIA_Wolf_ArmorM_AEXPANSION_15_00_DE";
    DIA_Wolf_ArmorM_AEXPANSION_04_01 = "DIA_Wolf_ArmorM_AEXPANSION_04_01_DE";
    DIA_Wolf_ArmorM_AEXPANSION_04_02 = "DIA_Wolf_ArmorM_AEXPANSION_04_02_DE";
    DIA_Wolf_ArmorM_AEXPANSION_04_03 = "DIA_Wolf_ArmorM_AEXPANSION_04_03_DE";
    DIA_Wolf_ArmorM_AEXPANSION_04_04 = "DIA_Wolf_ArmorM_AEXPANSION_04_04_DE";
    DIA_Wolf_BuyArmorMP_AEXPANSION_15_00 = "DIA_Wolf_BuyArmorMP_AEXPANSION_15_00_DE";
    DIA_Wolf_BuyArmorMP_AEXPANSION_04_01 = "DIA_Wolf_BuyArmorMP_AEXPANSION_04_01_DE";
    DIA_Wolf_BuyArmorMP_AEXPANSION_04_02 = "DIA_Wolf_BuyArmorMP_AEXPANSION_04_02_DE";
    DIA_Wolf_ArmorBow_AEXPANSION_15_00 = "DIA_Wolf_ArmorBow_AEXPANSION_15_00_DE";
    DIA_Wolf_ArmorBow_AEXPANSION_04_01 = "DIA_Wolf_ArmorBow_AEXPANSION_04_01_DE";
    DIA_Wolf_BuyArmorBow_AEXPANSION_15_00 = "DIA_Wolf_BuyArmorBow_AEXPANSION_15_00_DE";
    DIA_Wolf_BuyArmorBow_AEXPANSION_04_01 = "DIA_Wolf_BuyArmorBow_AEXPANSION_04_01_DE";
    DIA_Wolf_BuyArmorBow_AEXPANSION_04_02 = "DIA_Wolf_BuyArmorBow_AEXPANSION_04_02_DE";
    DIA_Wolf_AboutCrawler_AEXPANSION_15_00 = "DIA_Wolf_AboutCrawler_AEXPANSION_15_00_DE";
    DIA_Wolf_AboutCrawler_AEXPANSION_08_01 = "DIA_Wolf_AboutCrawler_AEXPANSION_08_01_DE";
};
